import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

import roster from "../../src/lib/constants/players-roster.json";
import {
  buildSourceInventory,
  inventoryCoverage,
  type RagSourceInventory,
  type RosterSourcePlayer,
} from "../../src/lib/baseball-qa/source-inventory";

// 기본 동작은 inventory-only다. 과거에 리뷰·머지된 bootstrap seed migration을
// 무옵션 실행이 조용히 덮어쓰던 것이 2026-08-01 P0의 재발 경로였다.
// seed 출력은 `--emit-seed`로만 열리고, 이미 존재하는 migration 덮어쓰기는 fail-close다.
const emitSeed = process.argv.includes("--emit-seed");
const allowSeedOverwrite = process.argv.includes("--allow-seed-overwrite");
const positional = process.argv.slice(2).filter((arg) => !arg.startsWith("--"));
const outputPath = resolve(
  process.cwd(),
  positional[0] ?? "data/baseball-qa/source-inventory.json",
);
const seedPath = resolve(
  process.cwd(),
  positional[1] ?? "supabase/migrations/20260731_baseball_genius_rag_sources_seed.sql",
);
if (emitSeed && existsSync(seedPath) && !allowSeedOverwrite) {
  console.error(
    `refusing to overwrite existing migration: ${seedPath}\n` +
      "기존 migration은 불변이다. 신규 source는 append-only migration으로 분리하고, " +
      "정말 bootstrap을 재생성해야 하면 --allow-seed-overwrite 를 명시하라.",
  );
  process.exit(1);
}
const previous = existsSync(outputPath)
  ? JSON.parse(readFileSync(outputPath, "utf8")) as RagSourceInventory
  : undefined;
const inventory = buildSourceInventory(roster as RosterSourcePlayer[], previous);

mkdirSync(dirname(outputPath), { recursive: true });
const serialized = [
  "{",
  `  \"schemaVersion\": ${inventory.schemaVersion},`,
  `  \"inventoryVersion\": ${JSON.stringify(inventory.inventoryVersion)},`,
  "  \"sources\": [",
  inventory.sources.map((source) => `    ${JSON.stringify(source)}`).join(",\n"),
  "  ]",
  "}",
  "",
].join("\n");
writeFileSync(outputPath, serialized);

function sqlString(value: string | null): string {
  return value === null ? "NULL" : `'${value.replaceAll("'", "''")}'`;
}

function sqlTextArray(values: string[]): string {
  return `ARRAY[${values.map(sqlString).join(",")}]::text[]`;
}

const seedRows = inventory.sources.map((source) => `  (${[
  sqlString(source.sourceKey),
  sqlString(source.sourceKind),
  sqlString(source.entityType),
  sqlString(source.entityId),
  sqlString(source.pageTitle),
  sqlTextArray(source.candidateUrls),
  sqlString(source.canonicalUrl),
  sqlString(source.resolutionStatus),
  sqlString(source.resolutionNote),
  sqlString(source.sourceGrade),
  sqlString(source.ingestionStatus),
  sqlString(source.identityFingerprint),
  `${sqlString(JSON.stringify(source.metadata))}::jsonb`,
].join(", ")})`);
const seedSql = `-- Generated by npm run build:baseball-source-inventory. Do not hand-edit.\n\n` +
  `INSERT INTO public.genius_rag_sources AS target (\n` +
  `  source_key, source_kind, entity_type, entity_id, page_title, candidate_urls,\n` +
  `  canonical_url, resolution_status, resolution_note, source_grade, ingestion_status,\n` +
  `  identity_fingerprint, metadata\n` +
  `) VALUES\n${seedRows.join(",\n")}\n` +
  `ON CONFLICT (source_key) DO UPDATE SET\n` +
  `  source_kind = EXCLUDED.source_kind,\n` +
  `  entity_type = EXCLUDED.entity_type,\n` +
  `  entity_id = EXCLUDED.entity_id,\n` +
  `  page_title = EXCLUDED.page_title,\n` +
  `  candidate_urls = EXCLUDED.candidate_urls,\n` +
  `  canonical_url = CASE WHEN target.identity_fingerprint = EXCLUDED.identity_fingerprint THEN target.canonical_url ELSE EXCLUDED.canonical_url END,\n` +
  `  resolution_status = CASE WHEN target.identity_fingerprint = EXCLUDED.identity_fingerprint THEN target.resolution_status ELSE EXCLUDED.resolution_status END,\n` +
  `  resolution_note = CASE WHEN target.identity_fingerprint = EXCLUDED.identity_fingerprint THEN target.resolution_note ELSE EXCLUDED.resolution_note END,\n` +
  `  source_grade = EXCLUDED.source_grade,\n` +
  `  ingestion_status = CASE WHEN target.identity_fingerprint = EXCLUDED.identity_fingerprint THEN target.ingestion_status ELSE 'not_started' END,\n` +
  `  ingestion_attempts = CASE WHEN target.identity_fingerprint = EXCLUDED.identity_fingerprint THEN target.ingestion_attempts ELSE 0 END,\n` +
  `  lease_until = CASE WHEN target.identity_fingerprint = EXCLUDED.identity_fingerprint THEN target.lease_until ELSE NULL END,\n` +
  `  claim_token = CASE WHEN target.identity_fingerprint = EXCLUDED.identity_fingerprint THEN target.claim_token ELSE NULL END,\n` +
  `  claim_generation = CASE WHEN target.identity_fingerprint = EXCLUDED.identity_fingerprint THEN target.claim_generation ELSE 0 END,\n` +
  `  revision = CASE WHEN target.identity_fingerprint = EXCLUDED.identity_fingerprint THEN target.revision ELSE NULL END,\n` +
  `  content_hash = CASE WHEN target.identity_fingerprint = EXCLUDED.identity_fingerprint THEN target.content_hash ELSE NULL END,\n` +
  `  crawled_at = CASE WHEN target.identity_fingerprint = EXCLUDED.identity_fingerprint THEN target.crawled_at ELSE NULL END,\n` +
  `  ingested_at = CASE WHEN target.identity_fingerprint = EXCLUDED.identity_fingerprint THEN target.ingested_at ELSE NULL END,\n` +
  `  stale_after = CASE WHEN target.identity_fingerprint = EXCLUDED.identity_fingerprint THEN target.stale_after ELSE NULL END,\n` +
  `  tombstoned_at = CASE WHEN target.identity_fingerprint = EXCLUDED.identity_fingerprint THEN target.tombstoned_at ELSE NULL END,\n` +
  `  last_error = CASE WHEN target.identity_fingerprint = EXCLUDED.identity_fingerprint THEN target.last_error ELSE NULL END,\n` +
  `  identity_fingerprint = EXCLUDED.identity_fingerprint,\n` +
  `  metadata = EXCLUDED.metadata,\n` +
  `  updated_at = now();\n`;
if (emitSeed) writeFileSync(seedPath, seedSql);

console.log(JSON.stringify({
  outputPath,
  inventoryVersion: inventory.inventoryVersion,
  sourceCount: inventory.sources.length,
  playerCoverage: inventoryCoverage(inventory),
  seedPath: emitSeed ? seedPath : null,
}, null, 2));
