-- Post-game reviews: service-only API boundary; no client-supplied identity/context.
-- Apply only after review. No changes to posts/comments or their existing triggers.
-- Contract / product decisions: https://app.notion.com/p/3d4c901bb37281349617ceeb287fd318
-- Proposal defaults (BEST minimum, recreation, nomination) live ONLY in
-- src/lib/game-reviews/policy.ts: trusted API -> RPC parameters, never SQL defaults.
-- Fixed v1 enforcement below: edit <10 minutes once (domain.ts EDIT_WINDOW_MS),
-- rolling 60s quotas create=3 / like=20 / comment=3 / comment_edit=3 / report=5;
-- comment writes also have a 10s cooldown and 5-minute duplicate-body protection.
-- Three distinct reporters trigger auto-hide (existing report-blind.ts contract).
-- Changing these fixed contracts requires a NEW migration plus matching domain/UI
-- and QA expectations; do not edit an already-applied migration to change policy.
-- Creation has no postgame N-day deadline in v1: the trusted route verifies final
-- status on every write. This is separate from the creation-relative edit window.
BEGIN;
CREATE TABLE public.game_reviews (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 game_id text NOT NULL CHECK (game_id ~ '^\d{8}[A-Z]{4}\d$'),
 author_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
 team_id integer NOT NULL,
 content text NOT NULL CHECK (length(btrim(content)) > 0 AND octet_length(content) <= 12800),
 player_key text, player_name text,
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 edited_at timestamptz, edit_count integer NOT NULL DEFAULT 0 CHECK (edit_count BETWEEN 0 AND 1),
 like_count integer NOT NULL DEFAULT 0 CHECK (like_count >= 0),
 is_hidden boolean NOT NULL DEFAULT false, deleted_at timestamptz,
 CHECK ((player_key IS NULL) = (player_name IS NULL))
);
-- At most one active original. Historical tombstones persist; the trusted
-- service policy below decides whether a deleted original permits a NEW id.
CREATE UNIQUE INDEX game_reviews_one_active ON public.game_reviews(game_id,author_id) WHERE deleted_at IS NULL;
CREATE INDEX game_reviews_participation ON public.game_reviews(game_id,author_id,id DESC);
CREATE INDEX game_reviews_feed ON public.game_reviews(game_id,id DESC) WHERE deleted_at IS NULL AND NOT is_hidden;
CREATE INDEX game_reviews_best ON public.game_reviews(game_id,team_id,like_count DESC,created_at,id) WHERE deleted_at IS NULL AND NOT is_hidden;
CREATE TABLE public.game_review_likes (
 review_id bigint NOT NULL REFERENCES public.game_reviews(id) ON DELETE CASCADE,
 user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(review_id,user_id)
);
CREATE TABLE public.game_review_comments (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 review_id bigint NOT NULL REFERENCES public.game_reviews(id) ON DELETE CASCADE,
 author_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
 content text NOT NULL CHECK (length(btrim(content)) > 0 AND octet_length(content) <= 25600),
 content_key text NOT NULL,
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(), edited_at timestamptz,
 is_hidden boolean NOT NULL DEFAULT false, deleted_at timestamptz
);
CREATE INDEX game_review_comments_feed ON public.game_review_comments(review_id,id DESC) WHERE deleted_at IS NULL AND NOT is_hidden;
CREATE INDEX game_review_comments_flood ON public.game_review_comments(author_id,created_at DESC);
-- A bounded rolling window per actor/action. Deletes/unlikes cannot reset limits.
CREATE TABLE public.game_review_rate_limits (
 actor_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, action text NOT NULL,
 hits timestamptz[] NOT NULL DEFAULT '{}', PRIMARY KEY(actor_id,action)
);
ALTER TABLE public.game_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.game_review_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.game_review_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.game_review_rate_limits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.game_reviews,public.game_review_likes,public.game_review_comments,public.game_review_rate_limits FROM PUBLIC,anon,authenticated;
GRANT ALL ON public.game_reviews,public.game_review_likes,public.game_review_comments,public.game_review_rate_limits TO service_role;
GRANT USAGE,SELECT ON SEQUENCE public.game_reviews_id_seq,public.game_review_comments_id_seq TO service_role;

-- Keep denormalized totals correct even when account deletion cascades likes.
CREATE FUNCTION public.gr_like_count() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
BEGIN
 IF TG_OP='INSERT' THEN UPDATE public.game_reviews SET like_count=like_count+1 WHERE id=NEW.review_id;
 ELSE UPDATE public.game_reviews SET like_count=like_count-1 WHERE id=OLD.review_id; END IF;
 RETURN NULL;
END $$;
CREATE TRIGGER trg_game_review_like_count AFTER INSERT OR DELETE ON public.game_review_likes FOR EACH ROW EXECUTE FUNCTION public.gr_like_count();

CREATE FUNCTION public.gr_blocked(a uuid,b uuid) RETURNS boolean LANGUAGE sql STABLE SET search_path=public,pg_temp AS $$
 SELECT EXISTS(SELECT 1 FROM public.user_blocks WHERE (blocker_id=a AND blocked_id=b) OR (blocker_id=b AND blocked_id=a))
$$;
CREATE FUNCTION public.gr_rate(a uuid,k text,lim integer,cooldown interval DEFAULT interval '0') RETURNS void
LANGUAGE plpgsql SET search_path=public,pg_temp AS $$
DECLARE t timestamptz:=clock_timestamp(); h timestamptz[];
BEGIN
 -- Caller serializes actor before any parent row lock.
 SELECT coalesce(array_agg(x ORDER BY x),'{}') INTO h FROM public.game_review_rate_limits r,
 unnest(r.hits) x WHERE r.actor_id=a AND r.action=k AND x>t-interval '60 seconds';
 IF cardinality(h)>=lim OR (cardinality(h)>0 AND h[cardinality(h)]>t-cooldown) THEN RAISE EXCEPTION 'gr_rate'; END IF;
 INSERT INTO public.game_review_rate_limits(actor_id,action,hits) VALUES(a,k,h||t)
 ON CONFLICT(actor_id,action) DO UPDATE SET hits=excluded.hits;
END $$;

-- Trusted route passes authoritative final-game teams and a verified participant snapshot.
CREATE FUNCTION public.gr_mutate(a uuid,g text,op text,rid bigint DEFAULT NULL,cid bigint DEFAULT NULL,
 body text DEFAULT NULL,body_key text DEFAULT NULL,desired boolean DEFAULT NULL,
 away integer DEFAULT NULL,home integer DEFAULT NULL,winner integer DEFAULT NULL,
 pkey text DEFAULT NULL,pname text DEFAULT NULL,p_allow_recreate boolean DEFAULT NULL,p_nomination_mode text DEFAULT NULL) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE r public.game_reviews; c public.game_review_comments; tid integer; t timestamptz;
BEGIN
 IF a IS NULL THEN RAISE EXCEPTION 'gr_auth'; END IF;
 IF op IN('create','edit') AND (p_allow_recreate IS NULL OR p_nomination_mode IS NULL OR p_nomination_mode NOT IN('disabled','optional_winner_participant','required_winner_participant')) THEN RAISE EXCEPTION 'gr_policy'; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended('gr_actor:'||a::text,0));
 SELECT team_id INTO tid FROM public.profiles WHERE id=a FOR SHARE;
 IF NOT FOUND THEN RAISE EXCEPTION 'gr_profile'; END IF;
 IF op='create' THEN
   IF EXISTS(SELECT 1 FROM public.game_reviews WHERE game_id=g AND author_id=a AND (deleted_at IS NULL OR NOT p_allow_recreate)) THEN RAISE EXCEPTION 'gr_exists'; END IF;
   IF tid IS NULL OR tid NOT IN(away,home) OR away IS NULL OR home IS NULL OR away=home THEN RAISE EXCEPTION 'gr_team'; END IF;
   IF pkey IS NOT NULL AND tid IS DISTINCT FROM winner THEN RAISE EXCEPTION 'gr_player'; END IF;
   IF p_nomination_mode='disabled' AND pkey IS NOT NULL THEN RAISE EXCEPTION 'gr_nomination_disabled'; END IF;
   IF p_nomination_mode='required_winner_participant' AND tid=winner AND pkey IS NULL THEN RAISE EXCEPTION 'gr_player_required'; END IF;
   PERFORM public.gr_rate(a,'create',3);
   INSERT INTO public.game_reviews(game_id,author_id,team_id,content,player_key,player_name)
   VALUES(g,a,tid,body,pkey,pname) RETURNING * INTO r;
 ELSIF op IN('edit','delete','like','comment','comment_edit','comment_delete') THEN
   SELECT * INTO r FROM public.game_reviews WHERE id=rid AND game_id=g FOR UPDATE;
   IF NOT FOUND THEN RAISE EXCEPTION 'gr_missing'; END IF;
   -- Owners may remove hidden originals. Tombstones are never revived in place.
   IF op='delete' AND r.author_id=a THEN
     UPDATE public.game_reviews SET deleted_at=coalesce(deleted_at,clock_timestamp()) WHERE id=r.id;
     RETURN jsonb_build_object('ok',true);
   END IF;
   IF r.deleted_at IS NOT NULL OR r.is_hidden OR public.gr_blocked(a,r.author_id) THEN RAISE EXCEPTION 'gr_missing'; END IF;
   t:=clock_timestamp();
   IF op='edit' THEN
     IF r.author_id<>a THEN RAISE EXCEPTION 'gr_owner'; END IF;
     IF r.content=body AND r.player_key IS NOT DISTINCT FROM pkey THEN RETURN jsonb_build_object('ok',true); END IF;
     IF r.edit_count<>0 OR t>=r.created_at+interval '10 minutes' THEN RAISE EXCEPTION 'gr_edit_expired'; END IF;
     IF pkey IS NOT NULL AND r.team_id IS DISTINCT FROM winner THEN RAISE EXCEPTION 'gr_player'; END IF;
     IF p_nomination_mode='disabled' AND pkey IS NOT NULL THEN RAISE EXCEPTION 'gr_nomination_disabled'; END IF;
     IF p_nomination_mode='required_winner_participant' AND r.team_id=winner AND pkey IS NULL THEN RAISE EXCEPTION 'gr_player_required'; END IF;
     UPDATE public.game_reviews SET content=body,player_key=pkey,player_name=pname,edit_count=1,edited_at=t WHERE id=r.id;
   ELSIF op='like' THEN
     IF r.author_id=a THEN RAISE EXCEPTION 'gr_self'; END IF;
     IF desired IS NULL THEN RAISE EXCEPTION 'gr_input'; END IF;
     IF desired IS DISTINCT FROM EXISTS(SELECT 1 FROM public.game_review_likes WHERE review_id=r.id AND user_id=a) THEN
       PERFORM public.gr_rate(a,'like',20);
       IF desired THEN
         INSERT INTO public.game_review_likes(review_id,user_id) VALUES(r.id,a);
       ELSE
         DELETE FROM public.game_review_likes WHERE review_id=r.id AND user_id=a;
       END IF;
     END IF;
   ELSIF op='comment' THEN
     PERFORM public.gr_rate(a,'comment',3,interval '10 seconds');
     IF EXISTS(SELECT 1 FROM public.game_review_comments WHERE author_id=a AND review_id=r.id AND content_key=body_key AND created_at>t-interval '5 minutes') THEN RAISE EXCEPTION 'gr_duplicate'; END IF;
     INSERT INTO public.game_review_comments(review_id,author_id,content,content_key) VALUES(r.id,a,body,body_key) RETURNING * INTO c;
   ELSIF op IN('comment_edit','comment_delete') THEN
     SELECT * INTO c FROM public.game_review_comments WHERE id=cid AND review_id=r.id FOR UPDATE;
     IF NOT FOUND OR c.deleted_at IS NOT NULL THEN RAISE EXCEPTION 'gr_missing'; END IF;
     IF c.author_id<>a THEN RAISE EXCEPTION 'gr_owner'; END IF;
     IF op='comment_delete' THEN UPDATE public.game_review_comments SET deleted_at=t WHERE id=c.id;
     ELSE
       IF c.is_hidden THEN RAISE EXCEPTION 'gr_missing'; END IF;
       IF c.content<>body THEN
         PERFORM public.gr_rate(a,'comment_edit',3,interval '10 seconds');
         UPDATE public.game_review_comments SET content=body,content_key=body_key,edited_at=t WHERE id=c.id;
       END IF;
     END IF;
   ELSE RAISE EXCEPTION 'gr_owner'; END IF;
 ELSE RAISE EXCEPTION 'gr_input'; END IF;
 RETURN jsonb_build_object('ok',true,'id',coalesce(c.id,r.id));
END $$;

CREATE FUNCTION public.gr_feed(g text,a uuid DEFAULT NULL,before_id bigint DEFAULT NULL,rid bigint DEFAULT NULL,filter_team integer DEFAULT NULL,p_best_min_likes integer DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE result jsonb;
BEGIN
 IF p_best_min_likes IS NULL OR p_best_min_likes<1 OR p_best_min_likes>10000 THEN RAISE EXCEPTION 'gr_policy'; END IF;
 IF rid IS NOT NULL THEN
   -- Hold the parent while reading children, so concurrent hide/delete cannot
   -- turn a checked parent into an invisible one between statements.
   PERFORM 1 FROM public.game_reviews WHERE id=rid AND game_id=g AND deleted_at IS NULL AND NOT is_hidden AND NOT public.gr_blocked(a,author_id) FOR SHARE;
   IF NOT FOUND THEN RAISE EXCEPTION 'gr_missing'; END IF;
   WITH visible AS (
     SELECT c.id,c.author_id,p.team_id,p.nickname,c.content,c.created_at,c.edited_at FROM public.game_review_comments c
     JOIN public.profiles p ON p.id=c.author_id
     WHERE c.review_id=rid AND c.deleted_at IS NULL AND NOT c.is_hidden AND NOT public.gr_blocked(a,c.author_id)
     AND (before_id IS NULL OR c.id<before_id) ORDER BY c.id DESC LIMIT 26
   ), page AS (SELECT * FROM visible ORDER BY id DESC LIMIT 25)
   SELECT jsonb_build_object('rows',coalesce((SELECT jsonb_agg(to_jsonb(page) ORDER BY id DESC) FROM page),'[]'),
    'review',(SELECT jsonb_build_object('id',r.id,'author_id',r.author_id,'team_id',r.team_id,'nickname',p.nickname,'content',r.content,
      'created_at',r.created_at,'edit_count',r.edit_count,'like_count',r.like_count,'player_key',r.player_key,'player_name',r.player_name,
      'liked',EXISTS(SELECT 1 FROM public.game_review_likes WHERE review_id=r.id AND user_id=a),
      'comment_count',(SELECT count(*) FROM public.game_review_comments c WHERE c.review_id=r.id AND c.deleted_at IS NULL AND NOT c.is_hidden AND NOT public.gr_blocked(a,c.author_id)))
      FROM public.game_reviews r JOIN public.profiles p ON p.id=r.author_id WHERE r.id=rid AND r.deleted_at IS NULL AND NOT r.is_hidden AND NOT public.gr_blocked(a,r.author_id)),
    'next',CASE WHEN (SELECT count(*) FROM visible)>25 THEN (SELECT min(id) FROM page) ELSE NULL END,
    'server_now',clock_timestamp()) INTO result;
   RETURN result;
 END IF;
 WITH visible AS MATERIALIZED (
   SELECT r.*,p.nickname FROM public.game_reviews r JOIN public.profiles p ON p.id=r.author_id
   WHERE r.game_id=g AND r.deleted_at IS NULL AND NOT r.is_hidden AND NOT public.gr_blocked(a,r.author_id)
 ), page AS (SELECT * FROM visible WHERE (before_id IS NULL OR id<before_id) AND (filter_team IS NULL OR team_id=filter_team) ORDER BY id DESC LIMIT 26),
 best AS (SELECT DISTINCT ON(team_id) * FROM visible WHERE like_count>=p_best_min_likes ORDER BY team_id,like_count DESC,created_at,id),
 needed AS (SELECT id FROM page UNION SELECT id FROM best UNION SELECT id FROM visible WHERE author_id=a),
 dto AS (
  SELECT v.id,v.author_id,v.team_id,v.nickname,v.content,v.created_at,v.edit_count,v.like_count,v.player_key,v.player_name,
  EXISTS(SELECT 1 FROM public.game_review_likes l WHERE l.review_id=v.id AND l.user_id=a) AS liked,
  (SELECT count(*) FROM public.game_review_comments c WHERE c.review_id=v.id AND c.deleted_at IS NULL AND NOT c.is_hidden AND NOT public.gr_blocked(a,c.author_id)) AS comment_count
  FROM visible v JOIN needed n ON n.id=v.id
 ), shown AS (SELECT dto.* FROM dto JOIN (SELECT id FROM page ORDER BY id DESC LIMIT 25) p USING(id))
 SELECT jsonb_build_object(
  'rows',coalesce((SELECT jsonb_agg(to_jsonb(shown) ORDER BY id DESC) FROM shown),'[]'),
  'best',coalesce((SELECT jsonb_agg(to_jsonb(dto) ORDER BY dto.team_id) FROM dto JOIN best USING(id)),'[]'),
  'total',(SELECT count(*) FROM visible),
  'team_counts',coalesce((SELECT jsonb_object_agg(team_id,n) FROM (SELECT team_id,count(*) n FROM visible GROUP BY team_id) counts),'{}'),
  'own',(SELECT jsonb_build_object('id',id,'hidden',is_hidden,'deleted',deleted_at IS NOT NULL) FROM public.game_reviews WHERE game_id=g AND author_id=a ORDER BY id DESC LIMIT 1),
  'ownReview',(SELECT to_jsonb(dto) FROM dto WHERE author_id=a),
  'next',CASE WHEN (SELECT count(*) FROM page)>25 THEN (SELECT min(id) FROM shown) ELSE NULL END,
  'server_now',clock_timestamp()) INTO result;
 RETURN result;
END $$;

-- Direct client writes to these report types are forbidden; other report policies unchanged.
CREATE POLICY game_review_report_service_only ON public.reports AS RESTRICTIVE FOR INSERT TO anon,authenticated
WITH CHECK(target_type NOT IN('game_review','game_review_comment'));

CREATE FUNCTION public.gr_report(a uuid,kind text,target bigint,why text,details text DEFAULT NULL) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE owner_id uuid; parent_id bigint;
BEGIN
 IF a IS NULL OR kind NOT IN('game_review','game_review_comment') OR why NOT IN('욕설·비하·혐오','광고·도배','개인정보 노출','기타 운영정책') THEN RAISE EXCEPTION 'gr_input'; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended('gr_actor:'||a::text,0));
 -- Same report lock before parent row lock in all reporting paths.
 PERFORM pg_advisory_xact_lock(hashtext('report_blind:'||kind||':'||target::text));
 IF kind='game_review' THEN parent_id:=target;
 ELSE SELECT review_id INTO parent_id FROM public.game_review_comments WHERE id=target; END IF;
 SELECT author_id INTO owner_id FROM public.game_reviews WHERE id=parent_id AND deleted_at IS NULL AND NOT is_hidden FOR UPDATE;
 IF NOT FOUND OR public.gr_blocked(a,owner_id) THEN RAISE EXCEPTION 'gr_missing'; END IF;
 IF kind='game_review_comment' THEN
   SELECT author_id INTO owner_id FROM public.game_review_comments WHERE id=target AND deleted_at IS NULL AND NOT is_hidden FOR UPDATE;
   IF NOT FOUND THEN RAISE EXCEPTION 'gr_missing'; END IF;
 END IF;
 IF owner_id=a THEN RAISE EXCEPTION 'gr_self'; END IF;
 IF public.gr_blocked(a,owner_id) THEN RAISE EXCEPTION 'gr_missing'; END IF;
 IF EXISTS(SELECT 1 FROM public.reports WHERE reporter_id=a AND target_type=kind AND target_id=target) THEN RAISE EXCEPTION 'gr_duplicate'; END IF;
 PERFORM public.gr_rate(a,'report',5);
 INSERT INTO public.reports(reporter_id,target_type,target_id,reason,detail) VALUES(a,kind,target,why,left(details,500));
END $$;

CREATE FUNCTION public.gr_auto_blind() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE n integer; owner_id uuid; parent_id bigint;
BEGIN
 IF NEW.target_type NOT IN('game_review','game_review_comment') OR NEW.reason='block' THEN RETURN NEW; END IF;
 PERFORM pg_advisory_xact_lock(hashtext('report_blind:'||NEW.target_type||':'||NEW.target_id::text));
 SELECT count(DISTINCT reporter_id) INTO n FROM public.reports WHERE target_type=NEW.target_type AND target_id=NEW.target_id AND reason<>'block';
 IF n<3 THEN RETURN NEW; END IF;
 IF NEW.target_type='game_review' THEN
   UPDATE public.game_reviews SET is_hidden=true WHERE id=NEW.target_id AND NOT is_hidden AND deleted_at IS NULL RETURNING author_id INTO owner_id;
 ELSE
   SELECT review_id INTO parent_id FROM public.game_review_comments WHERE id=NEW.target_id;
   PERFORM 1 FROM public.game_reviews WHERE id=parent_id FOR UPDATE;
   UPDATE public.game_review_comments SET is_hidden=true WHERE id=NEW.target_id AND NOT is_hidden AND deleted_at IS NULL RETURNING author_id INTO owner_id;
 END IF;
 IF owner_id IS NOT NULL THEN
   INSERT INTO public.report_blind_notices(target_type,target_id,author_id) VALUES(NEW.target_type,NEW.target_id,owner_id) ON CONFLICT(target_type,target_id) DO NOTHING;
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER trg_game_review_blind AFTER INSERT ON public.reports FOR EACH ROW EXECUTE FUNCTION public.gr_auto_blind();

CREATE FUNCTION public.gr_moderate(kind text,target bigint,hidden boolean) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE parent_id bigint;
BEGIN
 IF hidden IS NULL THEN RAISE EXCEPTION 'gr_input'; END IF;
 IF kind='game_review' THEN
   UPDATE public.game_reviews SET is_hidden=hidden WHERE id=target AND deleted_at IS NULL;
 ELSIF kind='game_review_comment' THEN
   SELECT review_id INTO parent_id FROM public.game_review_comments WHERE id=target;
   PERFORM 1 FROM public.game_reviews WHERE id=parent_id FOR UPDATE;
   UPDATE public.game_review_comments SET is_hidden=hidden WHERE id=target AND deleted_at IS NULL;
 ELSE RAISE EXCEPTION 'gr_input'; END IF;
 IF NOT FOUND THEN RAISE EXCEPTION 'gr_missing'; END IF;
END $$;

-- PostgreSQL defaults new functions to PUBLIC EXECUTE; explicitly close every helper.
DO $$ DECLARE f record; BEGIN
 FOR f IN SELECT oid::regprocedure AS signature FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname IN('gr_blocked','gr_rate','gr_mutate','gr_feed','gr_report','gr_auto_blind','gr_moderate','gr_like_count') LOOP
   EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,anon,authenticated',f.signature);
   EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO service_role',f.signature);
 END LOOP;
END $$;
COMMIT;
